spring:
  datasource:
    url: jdbc:mysql://${SPRING_DATASOURCE_HOST:mysql}:${SPRING_DATASOURCE_PORT:3306}/${SPRING_DATASOURCE_DB:blog}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 2000
      time-between-eviction-runs: 60000
      
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        time-between-eviction-runs: 60000
        max-wait: 2000ms

# 日志配置
logging:
  level:
    root: INFO
    com.my.blog: INFO

# Swagger配置
springdoc:
  swagger-ui:
    enabled: false  # 生产环境关闭